name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18
  JAVA_VERSION: '17'
  ANDROID_BUILD_TOOLS_VERSION: '34.0.0'
  ANDROID_SDK_VERSION: '34'
  NDK_VERSION: '23.1.7779620'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate JS Bundle
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/

      - name: Fix Gradle permissions
        run: chmod +x android/gradlew

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Build Android with Google Service
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > android/app/google-services.json
             cd android && ./gradlew assembleRelease --no-daemon --max-workers 2

      - name: Build Android Release Simple
        run: |
          cd android
          ./gradlew assembleRelease \
            --warning-mode all \
             -Dorg.gradle.java.home=$JAVA_HOME_17_X64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: android/app/build/outputs/apk/release/app-release.apk
